### ISSUE TITLE
Action mailer does not respect field order in the mail template

### ISSUE THREAD

**Issue by fredvd** [quintagroup/collective.easyform#17]
When I send an email using the mailer action the fields are not rendered in the order as they are in the form. It also doesn't make a difference if I select "Include all fields" or specify a specific order in the fields in/out widget. 

![email](https://cloud.githubusercontent.com/assets/394784/6289167/63955274-b91e-11e4-9795-95eb5c4f0c22.gif)

![actionsmailer](https://cloud.githubusercontent.com/assets/394784/6289136/2c6af1d2-b91e-11e4-9aaa-55115bd779aa.gif)

**Comment by fredvd** [comment]
The fields are passed to the template rendere wraped in a dict(), so it's not strange that the field order is lost (L 177, collective/easyform/actions.py):

       'fields': dict([(i, j.title) for i, j in getFieldsInOrder(schema)]),

But to simply change this to list and change the default mailer template in config.py probably will break installed base.... What to do?

**Comment by fredvd** [comment]
@kroman0 We have some resources available to fix issues in collective.easyform like these, but I'd like to get some feedback first on possible backwarts-incompatible choces like these.

**Comment by chervol** [comment]
@fredvd OrderedDict looks ok and it is like smaller change that will not require the rendering template modification. You are welcome to provide pull request.

**Comment by fredvd** [comment]
Sorry for not following up on this anymore, I talked about this with @mauritsvanrees : OrderedDict is fine but you would lose compatibility with python2.6 and hence Plone 4.1 / 4.2 . If this is ok with you then OrderedDict is fine indeed.

**Comment by chervol** [comment]
Good point. But Plone 4.1 / 4.2 are not supported anyway - we have tested easyform only starting with Plone 4.3. and Plone 5.

**Comment by chervol** [comment]
https://pypi.python.org/pypi/backport_collections - can be used to have OrderedDict on python 2.6.
