### ISSUE TITLE
"Edit XML Fields Model" doesn't work in Plone 5

### ISSUE THREAD

**Issue by sorenabell** [quintagroup/collective.easyform#19]
Button **Edit XML Fields Model** on the Fields editing page leads to an empty page. 

*collective.easyform 1.0a3
Plone 5.0b2 (5005)
CMF 2.2.8
Zope 2.13.22
Python 2.7.4 (default, Apr 9 2013, 10:22:26) [GCC 4.6.3 20120306 (Red Hat 4.6.3-2)]
PIL 2.7.0 (Pillow)*

**Comment by tkimnguyen** [comment]
With 5.0b4, I see the text field containing the XML but the text field and the Save button are not editable and disabled.

**Comment by frisi** [comment]
the same problem when using plone.app.widgets and easyform in plone 4.3.6.
might be fixed with https://github.com/plone/Products.CMFPlone/issues/895

**Comment by tkimnguyen** [comment]
This works with the coredev buildout as of September 30, 2015 so probably closable now.
