### ISSUE TITLE
Depend on CMFDefault which has been dropped from Plone 5

### ISSUE THREAD

**Issue by vangheem** [quintagroup/collective.easyform#20]
Plone 5 has removed the CMFDefault dependency but email validation depends on it for the exception. Should be removed.

**Comment by kroman0** [comment]
https://github.com/plone/Products.CMFPlone/commit/4bfd4cf1c6224f27553e1ee988447067447829be

**Comment by prakharjoshi** [comment]
I guess this is solved ? @kroman0

**Comment by kroman0** [comment]
Fixed.
