### ISSUE TITLE
please move this into the collective!

### ISSUE THREAD

**Issue by tkimnguyen** [quintagroup/collective.easyform#29]
would be nice if members of the collective could cut releases too - thx - this is a very nice add-on

**Comment by pbauer** [comment]
:+1:

**Comment by chervol** [comment]
Forked into collective: https://github.com/collective/collective.easyform
@tkimnguyen please let me know who needs to be added as release manager on pypi.

**Comment by pbauer** [comment]
@chervol Now it exists in two places and only one of them has the issues. imho that's suboptimal. Could you shutdown this repo and move the issues to the collective?

**Comment by tkimnguyen** [comment]
You can maybe recreate the issues yourself and tag the original poster and comment in the old issues with a link to the new issue. 

On Mar 3, 2016, at 7:46 AM, Philip Bauer <notifications@github.com> wrote:

@chervol Now it exists in two places and only one of them has the issues. imho that's suboptimal. Could you shutdown this repo and move the issues to the collective?

**Comment by davilima6** [comment]
+1 for closing this repo or at least the issues tracker, since it's been migrated and now is duplicated.
